### ISSUE TITLE
Default font dirs on Windows has wrong path

### ISSUE THREAD

**Issue by pi-kei** [tdewolff/font#6]
https://github.com/tdewolff/font/blob/b654fd8acba368a32d4c6cc85770f76dfb6d1831/system.go#L67-L77

In my case `sysRoot` equals to `C:\\Windows`, that leads to path in line 76 be `C:\\Windows\\Windows\\Fonts`. This path is wrong and does not exist. Correct path sould be `C:\\Windows\\Fonts`.

To fix this issue line 76 should be:
```golang
filepath.Join(filepath.VolumeName(sysRoot), "\\", "Windows", "Fonts")
```

**Comment by tdewolff** [comment]
Thanks, this is now fixed!

**Comment by pi-kei** [comment]
I guess there's still an issue with the path. Without explicitly adding backslash after volume name it will return `C:Windows\\Fonts`.
There's a discussion about this https://github.com/golang/go/issues/46990 that suggests to explicitly add backslash. Because both variants are valid but different paths, it must be specified. I've tested locally using go1.24.2 - it is still like this.

**Comment by tdewolff** [comment]
Okay, I've added a fix, is this working?

**Comment by pi-kei** [comment]
Now it is working as expected.
